update to COAWST_v3.2

diff --git a/WRF/configure b/WRF/configure
--- a/WRF/configure
+++ b/WRF/configure
@@ -6,6 +6,7 @@ thiscmd=$0
 
 FORTRAN_COMPILER_TIMER=""
 opt_level="-f"
+rword="-r4"
 print_usage=""
 chemistry=""
 wrf_core=""
@@ -19,6 +20,7 @@ while [ $# -ge 1 ]; do
       -help) print_usage="yes" ;;
       -os) shift ; WRF_OS=$1 ;;
       -mach) shift ; WRF_MACH=$1 ;;
+      -r8) rword="-r8" ;;
       -time) shift ; FORTRAN_COMPILER_TIMER=$1 ;;
       chem) WRF_CHEM=1  ;;
       kpp) WRF_KPP=1  ;;
@@ -36,7 +38,15 @@ while [ $# -ge 1 ]; do
     shift
 done
 if [ -n "$print_usage" ] ; then
+  echo ' '
+  echo '*****************************************************************************'
   echo usage: $thiscmd '[-d|-D|-s|-f|-os os|-mach mach|-time timecommand] [chem] [kpp]'
+  echo '-d    build with debugging information and no optimization'
+  echo '-D    build with -d AND floating traps, traceback, uninitialized variables'
+  echo '-r8   build with 8 byte reals'
+  echo '-help print this message'
+  echo '*****************************************************************************'
+  echo ' '
   exit 
 fi
 
@@ -491,8 +501,13 @@ if [ -n "$WRF_LOG_BUFFERING" ]; then
     compileflags="${compileflags}!-DWRF_LOG_BUFFERING=1"
   fi
 fi
+if [ -n "$PNETCDF_QUILT" ]; then
+  echo Enabling quilt_pnc I/O server implementation.
+  compileflags="${compileflags}!-DPNETCDF_QUILT=1"
+fi
 if [ -n "$WRF_NMM_CORE" ]; then
   if [ $WRF_NMM_CORE = 1 ]; then
+    export WRF_NMM_NEST=1
     if [ -n "$HWRF" ]; then
       if [ $HWRF = 1 ]; then
         echo building WRF with HWRF option
@@ -544,8 +559,24 @@ if [ -n "$WRF_NMM_CORE" -a -n "$WRF_CHEM" ]; then
   fi
 fi
 
-if [ `which timex` ] ; then
+type m4 > /dev/null
+if [ $? -ne 0 ] ; then
+  echo
+  echo "ERROR ERROR ERROR ERROR ERROR ERROR ERROR"
+  echo "'m4' utility not found! Can not configure."
+  echo
+  echo "If on an Ubuntu machine, use the command"
+  echo "         sudo apt-get install m4        "
+  echo "To download and install the 'm4' utility"
+  exit 1
+fi
+
+if command -v timex > /dev/null 2>&1; then
   FORTRAN_COMPILER_TIMER=timex
+  echo "Will use 'timex' to report timing information"
+elif command -v time > /dev/null 2>&1; then
+  FORTRAN_COMPILER_TIMER=time
+  echo "Will use 'time' to report timing information"
 fi
 
 # Found perl, so proceed with configuration
@@ -557,6 +588,7 @@ if test -n "$PERL" ; then
           -compileflags=$compileflags -opt_level=$opt_level -USENETCDFF=$USENETCDFF -time=$FORTRAN_COMPILER_TIMER \
           -wrf_core=$wrf_core -gpfs=$GPFS_PATH -curl=$CURL_PATH -dep_lib_path="$DEP_LIB_PATH"
      if test ! -f configure.wrf ; then
+       echo "configure.wrf not created! Exiting configure script..."
        exit 1
      fi
      if [ "$opt_level" = "-d" ] ; then
@@ -566,6 +598,17 @@ if test -n "$PERL" ; then
      if [ "$opt_level" = "-D" ] ; then
         sed -e 's/FCOPTIM[	 ]*=/& # /' -e '/FCDEBUG[	 ]*=/s/#//g' configure.wrf > configure.wrf.edit
         /bin/mv configure.wrf.edit configure.wrf
+     fi
+
+     # GNU has a funny way of doing promotion to real*8
+     if [ "$rword" = "-r8" ] ; then
+       srch=`grep -i "^SFC" configure.wrf | grep -i "gfortran"`
+       if [ -n "$srch" ] ; then
+         sed -e '/^PROMOTION/s/#//' configure.wrf > configure.wrf.edit
+       else
+         sed -e '/^RWORDSIZE/s/$(NATIVE_RWORDSIZE)/8/' configure.wrf > configure.wrf.edit
+       fi
+       /bin/mv configure.wrf.edit configure.wrf
      fi
    else
      WRF_OS=$os ; export WRF_OS
@@ -936,6 +979,48 @@ if [ $retval -ne 0 ] ; then
   echo "That may not be enough."
   echo " "
   echo "*****************************************************************************"
+fi
+
+# testing for Fortran 2003 FLUSH features
+make fortran_2003_flush_test > tools/fortran_2003_flush_test.log 2>&1
+rm -f tools/fortran_2003_flush_test.log
+retval=-1
+if [ -f tools/fortran_2003_flush_test.exe ] ; then
+  retval=0
+fi
+if [ $retval -ne 0 ] ; then
+  make fortran_2003_fflush_test > tools/fortran_2003_fflush_test.log 2>&1
+  rm -f tools/fortran_2003_fflush_test.log
+  retval=-1
+  if [ -f tools/fortran_2003_fflush_test.exe ] ; then
+    retval=0
+  fi
+  if [ $retval -eq 0 ] ; then
+    sed -e '/^ARCH_LOCAL/s/$/ -DUSE_FFLUSH/' configure.wrf > configure.wrf.edit
+    mv configure.wrf.edit configure.wrf
+    echo " "
+    echo " "
+    echo "************************** W A R N I N G ************************************"
+    echo " "
+    echo "There are some Fortran 2003 features in WRF that your compiler does not recognize"
+    echo "The standard FLUSH routine has been replaced by FFLUSH."
+    echo "That may not be enough."
+    echo " "
+    echo "*****************************************************************************"
+  fi
+  if [ $retval -ne 0 ] ; then
+    sed -e '/^ARCH_LOCAL/s/$/ -DNO_FLUSH_SUPPORT/' configure.wrf > configure.wrf.edit
+    mv configure.wrf.edit configure.wrf
+    echo " "
+    echo " "
+    echo "************************** W A R N I N G ************************************"
+    echo " "
+    echo "There are some Fortran 2003 features in WRF that your compiler does not recognize"
+    echo "The standard FLUSH routine has been stubbed out."
+    echo "That may not be enough."
+    echo " "
+    echo "*****************************************************************************"
+  fi
 fi
 
 # testing for netcdf4 IO features
